Create .eslintrc
namshi/coding-standards pull request #15
Opened 2018-02-08 12:11 UTC by hossam-fares

As we discussed with @namshi/backend-read
this is the `.eslintrc` file for code styles, It's driven from [google eslint](https://github.com/google/eslint-config-google/blob/master/index.js)

2018-02-08 12:13 UTC, nerac approved these changes

2018-02-08 12:16 UTC, joejean approved these changes
Let's try this and see how it goes. We can change it according to feedback.

2018-02-11 11:48 UTC, geshan commented on jsSupportFiles/install-precommit-commands.js
> + * I think it will be a good option if we can set it up in our repos ( though pre-commit scripts/hook ), so that we don’t need to worry about the code-formatting issues anymore.
Through/using

2018-02-11 11:51 UTC, geshan requested changes
minor thing

2018-02-11 13:12 UTC, geshan approved these changes

2018-02-11 13:12 UTC, merged

2018-02-11 15:45 UTC, cirpo commented
LGTM 👍

2018-02-11 16:58 UTC, hossam-fares commented
Thanks Cirpo

On 11 Feb 2018 7:45 pm, "cirpo" <notifications@github.com> wrote:

> LGTM 👍
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/namshi/coding-standards/pull/15#issuecomment-364761112>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABw8xa8n4Mu0iNQZDY-mD4BkGSJ6BdPmks5tTwsagaJpZM4R-QCd>
> .
>

2018-02-12 07:10 UTC, shidhincr commented
👏

2018-02-12 10:40 UTC, cirpo commented
:D 
Miss you guys! Keep rocking!

2018-02-12 10:44 UTC, hossam-fares commented
Same here :)